Repository tektoncd/website, pull requests merged in 2019-04, with the labels that each got.

#7 Add initial OWNER files
  OWNERS
Labels: lgtm, size/XS

#4 Added quick start guide to ReadMe
  README.md
Labels: approved, lgtm, size/XS

#8 Add basic Tekton docs 📝
  .github/issue-template.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  code-of-conduct.md
Labels: approved, lgtm, size/L
