Repository tektoncd/website, pull requests merged in 2020-07, with the labels that each got.

#154 Fix path to Triggers yaml files in sync config
  sync/config/triggers.yaml
Labels: approved, lgtm, size/XS

#153 Change "kubernetes native" to "cloud native" ☁️
  config.toml
  content/en/_index.html
  content/en/docs/Concepts/_index.md
  content/en/docs/_index.md
Labels: approved, lgtm, size/XS

#152 Update image URLs in dashboard Katacoda tutorial
  tutorials/katacoda/tekton-dashboard/assets/create-pipeline-resource-form.png
  tutorials/katacoda/tekton-dashboard/assets/create-pipeline-run-form.png
  tutorials/katacoda/tekton-dashboard/assets/created-pipeline-resource.png
  tutorials/katacoda/tekton-dashboard/assets/created-pipeline-run.png
  tutorials/katacoda/tekton-dashboard/assets/dashboard-homepage.png
  tutorials/katacoda/tekton-dashboard/assets/import-pipelinerun-logs.png
  tutorials/katacoda/tekton-dashboard/assets/import-tekton-resources.png
  tutorials/katacoda/tekton-dashboard/assets/pipeline-resources-page.png
  tutorials/katacoda/tekton-dashboard/assets/pipeline-run-completed.png
  tutorials/katacoda/tekton-dashboard/assets/pipeline-run-created-notification.png
  tutorials/katacoda/tekton-dashboard/assets/pipeline-run-running.png
  tutorials/katacoda/tekton-dashboard/assets/pipeline-runs-page.png
  tutorials/katacoda/tekton-dashboard/assets/view-myapp.png
  tutorials/katacoda/tekton-dashboard/assets/view-status-of-pipeline0.png
  tutorials/katacoda/tekton-dashboard/step1.md
  tutorials/katacoda/tekton-dashboard/step2.md
  tutorials/katacoda/tekton-dashboard/step3.md
  tutorials/katacoda/tekton-dashboard/step4.md
  tutorials/katacoda/tekton-dashboard/step5.md
Labels: approved, lgtm, size/S

#119 add --dry-run option to command
  content/en/docs/Getting Started/_index.md
Labels: approved, lgtm, ok-to-test, size/XS
