Repository tektoncd/website, pull requests merged in 2020-04, with the labels that each got.

#74 Sync workspaces doc
  sync/config/pipelines.yaml
Labels: approved, lgtm, size/XS

#72 Fixed a typo
  content/en/docs/_index.md
Labels: approved, lgtm, size/XS

#80 typo: change cookiies to cookies
  layouts/partials/privacy-notice.html
Labels: approved, lgtm, size/XS

#75 Updated installation instructions for OpenShift
  content/en/docs/Getting Started/_index.md
Labels: approved, lgtm, size/S

#82 Update Kubernetes Version Information for Getting Started
  content/en/docs/Getting Started/_index.md
Labels: approved, lgtm, size/XS

#83 Fixed some typos in the Concepts section
  content/en/docs/Concepts/_index.md
Labels: approved, lgtm, size/XS

#86 Fix typo in asciinema script
  asciinema/scenario.sh
Labels: approved, lgtm, size/XS

#69 Add sbwsg and AlanGreene as OWNERS 🎉
  OWNERS
Labels: approved, lgtm, size/XS

#68 Add CLI to sync 👼
  sync/config/cli.yaml
Labels: approved, lgtm, size/M

#62 Change the url for releases
  content/en/docs/Dashboard/_index.md
Labels: approved, lgtm, size/XS

#79 Changed some v1alpha1 in Getting Started
  content/en/docs/Getting Started/_index.md
Labels: approved, lgtm, size/XS

#87 fix dashboard doc links and port
  content/en/docs/Dashboard/_index.md
Labels: approved, lgtm, size/S

#92 Typo fixed
  content/en/docs/Concepts/_index.md
Labels: approved, lgtm, size/XS

#91 Include tkn start in Getting Started Section and Remove Need to Save TaskRun to Local File
  content/en/docs/Getting Started/_index.md
Labels: approved, lgtm, size/M

#95 Add missing YAML files to Triggers sync config
  sync/config/triggers.yaml
Labels: approved, lgtm, size/XS
