Repository tektoncd/website, pull requests merged in 2020-10, with the labels that each got.

#179 Add the events page to pipeline docs
  sync/config/pipelines.yaml
Labels: approved, lgtm, size/XS

#180 Change from releases to versions
  layouts/partials/navbar-version-selector-docs.html
  templates/version-switcher.js.template
Labels: approved, lgtm, size/XS

#181 refactor sync script
  .gitignore
  runtime.txt
  static/images/mental_model.png
  sync/README.md
  sync/requirements.txt
  sync/runtime.txt
  sync/sync.py
  sync/test_sync.py
Labels: approved, lgtm, size/XL

#182 Further cleanup the sync script
  sync/config/cli.yaml
  sync/config/pipelines.yaml
  sync/config/triggers.yaml
  sync/sync.py
  sync/test_sync.py
Labels: approved, kind/cleanup, lgtm, size/L

#183 Add a script to add versions to sync configuration
  sync/README.md
  sync/config/cli.yaml
  sync/config/pipelines.yaml
  sync/config/triggers.yaml
  sync/requirements.txt
  sync/sync.py
  sync/test_sync.py
  sync/test_versions.py
  sync/versions.py
Labels: approved, kind/misc, lgtm, size/L

#184 Speed up things with parallel processing
  sync/sync.py
Labels: approved, lgtm, size/M

#185 Rewrite the link re-writing logic
  sync/sync.py
  sync/test-content/content.md
  sync/test-content/test.txt
  sync/test_sync.py
Labels: approved, kind/documentation, lgtm, size/L

#187 Use a trailing slash for the rewrite URL
  sync/sync.py
  sync/test_sync.py
Labels: approved, kind/misc, lgtm, size/S

#188 Adding Napoleon as an owner
  OWNERS
Labels: approved, lgtm, size/XS

#189 Lowercase fragments on local markdown pages
  sync/sync.py
  sync/test_sync.py
  sync/test_versions.py
Labels: approved, kind/bug, lgtm, size/M
