Repository tektoncd/website, pull requests merged in 2020-06, with the labels that each got.

#131 A few typos in Concepts/_index
  content/en/docs/Concepts/_index.md
Labels: approved, lgtm, size/XS

#138 Adding a resource to CONTRIBUTING.MD
  CONTRIBUTING.md
Labels: approved, lgtm, ok-to-test, size/XS

#139 Add guidance for formatting lists.
  content/en/doc-con-formatting.md
Labels: approved, lgtm, size/S

#142 Add a katacoda.yaml to store tutorial in a folder
  katacoda.yaml
  tutorials/katacoda/.keep
Labels: approved, lgtm, size/XS

#123 Added a Pipeline example to getting started
  content/en/docs/Getting Started/_index.md
  content/en/docs/Getting Started/pipelines.md
Labels: approved, lgtm, size/L

#135 Dockerize sync tool.
  requirements.txt
  runtime.txt
  sync/Dockerfile
  sync/README.md
  sync/requirements.txt
  sync/runtime.txt
  sync/sync.py
Labels: approved, lgtm, size/M

#143 Moving the tutorials over to the tekton namespace
  tutorials/katacoda/basic-pipeline/finish.md
  tutorials/katacoda/basic-pipeline/index.json
  tutorials/katacoda/basic-pipeline/init.sh
  tutorials/katacoda/basic-pipeline/intro.md
  tutorials/katacoda/basic-pipeline/step1.md
  tutorials/katacoda/basic-pipeline/step2.md
  tutorials/katacoda/basic-pipeline/step3.md
  tutorials/katacoda/tekton-dashboard/finish.md
  tutorials/katacoda/tekton-dashboard/images/create-pipeline-resource-form.png
  tutorials/katacoda/tekton-dashboard/images/create-pipeline-run-form.png
  tutorials/katacoda/tekton-dashboard/images/created-pipeline-resource.png
  tutorials/katacoda/tekton-dashboard/images/created-pipeline-run.png
  tutorials/katacoda/tekton-dashboard/images/dashboard-homepage.png
  tutorials/katacoda/tekton-dashboard/images/import-pipelinerun-logs.png
  tutorials/katacoda/tekton-dashboard/images/import-tekton-resources.png
  tutorials/katacoda/tekton-dashboard/images/pipeline-resources-page.png
  tutorials/katacoda/tekton-dashboard/images/pipeline-run-completed.png
  tutorials/katacoda/tekton-dashboard/images/pipeline-run-created-notification.png
  tutorials/katacoda/tekton-dashboard/images/pipeline-run-running.png
  tutorials/katacoda/tekton-dashboard/images/pipeline-runs-page.png
  tutorials/katacoda/tekton-dashboard/images/view-myapp.png
  tutorials/katacoda/tekton-dashboard/images/view-status-of-pipeline0.png
  tutorials/katacoda/tekton-dashboard/index.json
  tutorials/katacoda/tekton-dashboard/init.sh
  tutorials/katacoda/tekton-dashboard/intro.md
  tutorials/katacoda/tekton-dashboard/myapp/app.js
  tutorials/katacoda/tekton-dashboard/myapp/package.json
  tutorials/katacoda/tekton-dashboard/step1.md
  tutorials/katacoda/tekton-dashboard/step2.md
  tutorials/katacoda/tekton-dashboard/step3.md
  tutorials/katacoda/tekton-dashboard/step4.md
  tutorials/katacoda/tekton-dashboard/step5.md
Labels: approved, lgtm, size/XL

#136 Add steps to docs for running website dev envrioment locally
  DEVELOPMENT.md
  Makefile
Labels: approved, lgtm, size/M

#150 Fix pipeline-hello-goodbye.yaml
  content/en/docs/Getting Started/pipelines.md
Labels: approved, lgtm, size/XS

#151 Updated goodbye world example so that it matches the hello world example
  content/en/docs/Getting Started/pipelines.md
Labels: approved, lgtm, size/XS
