Repository tektoncd/website, pull requests merged in 2020-03, with the labels that each got.

#31 Added _index.md to docs/
  content/en/docs/_index.md
Labels: approved, lgtm, size/S

#39 Update DEVELOPMENT.md to describe netlify workflow
  DEVELOPMENT.md
  sync/sync.py
Labels: approved, lgtm, size/M

#41 Replace other tutorials with dashboard tutorial
  layouts/try/baseof.html
Labels: approved, lgtm, size/L

#46 Add afrittoli as OWNER
  OWNERS
Labels: approved, lgtm, size/XS

#47 Add skaegi as OWNER
  OWNERS
Labels: approved, lgtm, size/XS

#50 Add the Tekton logo to the main page
  layouts/shortcodes/blocks/cover.html
  static/images/tekton-horizontal-color.png
  static/stylesheets/tabs.css
Labels: approved, lgtm, size/XS

#49 Transform markdown links to hugo style
  .gitignore
  sync/sync.py
Labels: approved, lgtm, size/S

#51 Add Tekton favicon
  static/favicons/favicon-16x16.png
  static/favicons/favicon-32x32.png
  static/favicons/favicon.ico
Labels: approved, lgtm, size/XS

#52 Adds Linux foundation copyright, privacy, and terms footer
  config.toml
  i18n/en.toml
  layouts/partials/footer.html
  static/favicon.ico
  static/stylesheets/tabs.css
Labels: approved, lgtm, size/M

#53 Move default docs location to tektoncd master
  sync/config/pipelines.yaml
  sync/config/triggers.yaml
Labels: approved, lgtm, size/S

#55 Split `serve` and sync and reuse-sync 🔍
  Makefile
Labels: approved, lgtm, size/S

#56 sync: remove unused imports 😛
  sync/sync.py
Labels: approved, lgtm, size/XS

#59 serve: add --watch to live-rebuild
  Makefile
Labels: approved, lgtm, size/XS

#60 Fix sync.py doc to reference "sync" instead of "helper"
  sync/README.md
  sync/config/README.md
  templates/README.md
Labels: approved, lgtm, size/XS

#58 sync: allow nested dirs 😅
  sync/sync.py
Labels: approved, lgtm, size/XS
