Repository tektoncd/website, pull requests merged in 2020-11, with the labels that each got.

#192 Add a nightly deployment for the website
  .github/workflows/nightly-deploy.yml
Labels: approved, kind/misc, lgtm, size/S

#201 Replace pipelines v0.17.2 with v0.17.3
  sync/config/pipelines.yaml
Labels: approved, kind/documentation, lgtm, size/XS

#193 Add a version rm command to versions
  sync/README.md
  sync/requirements.txt
  sync/sync.py
  sync/test_sync.py
  sync/test_versions.py
  sync/versions.py
Labels: approved, kind/feature, lgtm, size/L

#200 Finetune .gitignore
  .gitignore
Labels: approved, kind/misc, lgtm, size/S

#203 Switch sync config from files to folders
  .gitignore
  sync/README.md
  sync/config/README.md
  sync/config/cli.yaml
  sync/config/pipelines.yaml
  sync/config/triggers.yaml
  sync/requirements.txt
  sync/sync.py
  sync/test-content/nested/another.md
  sync/test-content/nested/content.md
  sync/test-content/unwanted.txt
  sync/test_sync.py
  sync/test_versions.py
  sync/versions.py
Labels: approved, kind/feature, lgtm, size/XXL

#204 Fix the case of non-md files in nested folders
  sync/sync.py
  sync/test-content/nested/example.yaml
  sync/test_sync.py
Labels: approved, kind/bug, lgtm, size/S

#210 Add docs for pipeline v0.18.0
  Makefile
  sync/config/pipelines.yaml
  sync/config/triggers.yaml
  sync/sync.py
Labels: approved, kind/documentation, lgtm, size/L

#212 Try utf-8 first when decoding text
  sync/sync.py
Labels: approved, kind/bug, lgtm, size/XS

#214 Updating Overview section of Tekton
  content/en/docs/Overview/_index.md
Labels: approved, kind/misc, lgtm, size/XS

#219 Switch pipeline docs from v0.18.0 to v0.18.1
  sync/config/pipelines.yaml
Labels: approved, lgtm, size/XS

#220 Fix the baseURL for dev and prod use caes
  Makefile
  netlify.toml
Labels: approved, lgtm, size/S

#221 Enable index, follow in the production website
  netlify.toml
Labels: approved, lgtm, size/S
