Repository tektoncd/website, pull requests merged in 2020-09, with the labels that each got.

#166 Fix typo in _index.md
  content/en/docs/Getting Started/_index.md
Labels: approved, lgtm, size/XS

#167 Remove vendor-specific cluster setup instructions
  content/en/docs/Getting Started/_index.md
Labels: approved, lgtm, size/M

#168 Publish an overview of Tekton
  content/en/docs/getting-started-overview.md
Labels: approved, kind/documentation, lgtm, size/L

#171 remove modal from interactive tutorials
  assets/js/launch-tutorial.js
  layouts/docs/baseof.html
  layouts/shortcodes/tutorial.html
  layouts/try/baseof.html
Labels: approved, lgtm, size/M
