Repository tektoncd/website, pull requests merged in 2020-05, with the labels that each got.

#85 fix the link of github and qwiklabs
  assets/js/launch-tutorial.js
Labels: approved, kind/documentation, lgtm, size/XS

#97 Update clickable text pointing to 'Try' page
  content/en/docs/_index.md
Labels: approved, lgtm, size/XS

#100 Add the Tekton Documentation Contributor's Guide and Style Guide.
  content/en/doc-con-content.md
  content/en/doc-con-formatting.md
  content/en/doc-con-main.md
  content/en/doc-con-writing.md
Labels: approved, lgtm, size/XL

#107 Fix Website Responsiveness
  assets/scss/_styles_project.scss
  assets/scss/_variables_project.scss
  layouts/partials/privacy-notice.html
  layouts/shortcodes/blocks/cover.html
Labels: approved, lgtm, size/M

#112 Fix more username formatting.
  content/en/doc-con-writing.md
Labels: approved, lgtm, size/XS

#111 Fix username formatting.
  content/en/doc-con-main.md
Labels: approved, lgtm, size/XS

#110 Update 'Edit this page' link to point to correct project repo
  config.toml
  themes/docsy/layouts/partials/page-meta-links.html
Labels: approved, lgtm, size/S

#116 Remove sbwsg from OWNERS
  OWNERS
Labels: approved, kind/misc, lgtm, size/XS

#124 Fix spelling error
  content/en/_index.html
Labels: approved, lgtm, size/XS

#114 Fix css from breaking for different browsers.
  layouts/partials/footer.html
  layouts/shortcodes/blocks/manifesto.html
  layouts/shortcodes/blocks/partners-alternate.html
  layouts/shortcodes/blocks/showcase.html
Labels: approved, lgtm, size/S

#121 Update _index.md
  content/en/docs/Getting Started/_index.md
Labels: approved, lgtm, size/XS

#127 Sync missing docs from pipeline repo
  sync/config/pipelines.yaml
Labels: approved, lgtm, size/XS
