Repository tektoncd/website, pull requests merged in 2021-11, with the labels that each got.

#311 Add triggers v0.17 and v0.16.1
  sync/config/triggers.yaml
Labels: lgtm, approved, size/S

#314 Match the remote ref names when looking for branches
  sync/README.md
  sync/config/operator.yaml
  sync/config/pipelines.yaml
  sync/config/triggers.yaml
  sync/sync.py
  sync/test_sync.py
Labels: lgtm, approved, size/L

#316 Enable emoji for hugo
  config.toml
Labels: size/XS, lgtm, approved

#317 Enable netlify-plugin-checklinks
  .gitignore
  netlify.toml
Labels: lgtm, approved, size/S

#319 Point the pipeline config to release branch for v0.25
  sync/config/pipelines.yaml
Labels: size/XS, lgtm, approved

#324 Cleanup unused configs in sync.py
  sync/README.md
  sync/config/README.md
  sync/config/cli.yaml
  sync/config/operator.yaml
  sync/config/pipelines.yaml
  sync/config/triggers.yaml
  sync/sync.py
  sync/test_sync.py
  sync/test_versions.py
Labels: lgtm, approved, size/M

#325 Add support for non text/markdown mime types
  sync/sync.py
  sync/test-content/tekton.png
  sync/test_sync.py
Labels: lgtm, approved, size/M

#322 Add config for chains
  .gitignore
  sync/config/chains.yaml
  sync/sync.py
Labels: lgtm, approved, size/M

#328 Add geriom to the OWNERS file
  OWNERS
Labels: size/XS, lgtm, approved

#326 Pin python version in getting started tutorial
  tutorials/katacoda/getting-started/src/tekton-katacoda/tasks/build.yaml
  tutorials/katacoda/getting-started/tasks.md
Labels: size/XS, lgtm, approved
