Repository tektoncd/website, pull requests merged in 2021-03, with the labels that each got.

#238 Renaming branches: handling dashboard repository
  content/en/docs/Overview/_index.md
Labels: approved, lgtm, size/XS

#251 Add sync documentation for configuring subdirectories.
  sync/config/README.md
Labels: approved, lgtm, size/S

#234 Renaming branches: handling pipeline repository
  content/en/docs/Getting Started/_index.md
  content/en/docs/Overview/_index.md
  sync/config/pipelines.yaml
  tutorials/katacoda/dashboard/step1.md
  tutorials/katacoda/playground/step1.md
Labels: approved, lgtm, size/M

#257 Updated sentence so that it reads a little bit better
  tutorials/katacoda/getting-started/tasks.md
Labels: approved, lgtm, size/XS

#237 Renaming branches: handling hub repository
  content/en/docs/Overview/_index.md
Labels: approved, lgtm, size/XS
