Repository tektoncd/website, pull requests merged in 2021-01, with the labels that each got.

#223 Update Dashboard tutorial to latest versions
  tutorials/katacoda/tekton-dashboard/assets/create-pipeline-resource-form.jpg
  tutorials/katacoda/tekton-dashboard/assets/create-pipeline-resource-form.png
  tutorials/katacoda/tekton-dashboard/assets/create-pipeline-run-form.jpg
  tutorials/katacoda/tekton-dashboard/assets/create-pipeline-run-form.png
  tutorials/katacoda/tekton-dashboard/assets/created-pipeline-resource.jpg
  tutorials/katacoda/tekton-dashboard/assets/created-pipeline-resource.png
  tutorials/katacoda/tekton-dashboard/assets/created-pipeline-run.jpg
  tutorials/katacoda/tekton-dashboard/assets/created-pipeline-run.png
  tutorials/katacoda/tekton-dashboard/assets/dashboard-homepage.jpg
  tutorials/katacoda/tekton-dashboard/assets/dashboard-homepage.png
  tutorials/katacoda/tekton-dashboard/assets/import-pipelinerun-logs.jpg
  tutorials/katacoda/tekton-dashboard/assets/import-pipelinerun-logs.png
  tutorials/katacoda/tekton-dashboard/assets/import-tekton-resources.jpg
  tutorials/katacoda/tekton-dashboard/assets/import-tekton-resources.png
  tutorials/katacoda/tekton-dashboard/assets/pipeline-resources-page.jpg
  tutorials/katacoda/tekton-dashboard/assets/pipeline-resources-page.png
  tutorials/katacoda/tekton-dashboard/assets/pipeline-run-completed.jpg
  tutorials/katacoda/tekton-dashboard/assets/pipeline-run-completed.png
  tutorials/katacoda/tekton-dashboard/assets/pipeline-run-created-notification.jpg
  tutorials/katacoda/tekton-dashboard/assets/pipeline-run-created-notification.png
  tutorials/katacoda/tekton-dashboard/assets/pipeline-run-running.jpg
  tutorials/katacoda/tekton-dashboard/assets/pipeline-run-running.png
  tutorials/katacoda/tekton-dashboard/assets/pipeline-runs-page.jpg
  tutorials/katacoda/tekton-dashboard/assets/pipeline-runs-page.png
  tutorials/katacoda/tekton-dashboard/assets/view-myapp.jpg
  tutorials/katacoda/tekton-dashboard/assets/view-myapp.png
  tutorials/katacoda/tekton-dashboard/assets/view-status-of-pipeline0.jpg
  tutorials/katacoda/tekton-dashboard/assets/view-status-of-pipeline0.png
  tutorials/katacoda/tekton-dashboard/step1.md
  tutorials/katacoda/tekton-dashboard/step2.md
  tutorials/katacoda/tekton-dashboard/step3.md
  tutorials/katacoda/tekton-dashboard/step4.md
  tutorials/katacoda/tekton-dashboard/step5.md
Labels: approved, lgtm, size/M

#227 Update katacoda playground to latest releases
  tutorials/katacoda/playground/background.sh
Labels: approved, lgtm, size/XS

#228 Update links to Katacoda tutorials to point to official versions
  content/en/_index.html
  content/en/docs/Getting Started/_index.md
  layouts/shortcodes/tutorial.html
  layouts/try/baseof.html
  tutorials/katacoda/dashboard/assets/create-pipeline-resource-form.jpg
  tutorials/katacoda/dashboard/assets/create-pipeline-run-form.jpg
  tutorials/katacoda/dashboard/assets/created-pipeline-resource.jpg
  tutorials/katacoda/dashboard/assets/created-pipeline-run.jpg
  tutorials/katacoda/dashboard/assets/dashboard-homepage.jpg
  tutorials/katacoda/dashboard/assets/import-pipelinerun-logs.jpg
  tutorials/katacoda/dashboard/assets/import-tekton-resources.jpg
  tutorials/katacoda/dashboard/assets/pipeline-resources-page.jpg
  tutorials/katacoda/dashboard/assets/pipeline-run-completed.jpg
  tutorials/katacoda/dashboard/assets/pipeline-run-created-notification.jpg
  tutorials/katacoda/dashboard/assets/pipeline-run-running.jpg
  tutorials/katacoda/dashboard/assets/pipeline-runs-page.jpg
  tutorials/katacoda/dashboard/assets/view-myapp.jpg
  tutorials/katacoda/dashboard/assets/view-status-of-pipeline0.jpg
  tutorials/katacoda/dashboard/finish.md
  tutorials/katacoda/dashboard/index.json
  tutorials/katacoda/dashboard/init.sh
  tutorials/katacoda/dashboard/intro.md
  tutorials/katacoda/dashboard/myapp/app.js
  tutorials/katacoda/dashboard/myapp/package.json
  tutorials/katacoda/dashboard/step1.md
  tutorials/katacoda/dashboard/step2.md
  tutorials/katacoda/dashboard/step3.md
  tutorials/katacoda/dashboard/step4.md
  tutorials/katacoda/dashboard/step5.md
Labels: approved, lgtm, size/S

#226 Minor update to the docs of the versions script
  sync/README.md
Labels: approved, lgtm, size/S
