Repository tektoncd/website, pull requests merged in 2021-06, with the labels that each got.

#275 Update katacoda tutorials to use 'latest' releases of Pipelines and Dashboard
  tutorials/katacoda/basic-pipeline/init.sh
  tutorials/katacoda/dashboard/assets/create-pipeline-resource-form.jpg
  tutorials/katacoda/dashboard/assets/pipeline-run-created-notification.jpg
  tutorials/katacoda/dashboard/init.sh
  tutorials/katacoda/dashboard/step1.md
  tutorials/katacoda/dashboard/step3.md
  tutorials/katacoda/dashboard/step5.md
  tutorials/katacoda/playground/background.sh
Labels: approved, lgtm, size/M

#272 Updated copr info for current Fedora releases
  content/en/docs/Getting Started/_index.md
Labels: approved, lgtm, size/XS

#277 Pipeline docs v0.24 and v0.25
  sync/config/pipelines.yaml
Labels: approved, lgtm, size/S

#270 Add triggers v0.11.2, v0.12.1, v0.13.0 and v0.14.1
  sync/config/triggers.yaml
Labels: approved, lgtm, size/M

#276 Use branch refs in pipeline sync config
  sync/config/pipelines.yaml
Labels: approved, lgtm, size/S

#278 Fix kind of resource definition
  content/en/docs/Getting Started/pipelines.md
Labels: approved, lgtm, size/XS
