Repository tektoncd/website, pull requests merged in 2021-02, with the labels that each got.

#222 Add version v0.10.1 of triggers
  sync/config/triggers.yaml
Labels: approved, lgtm, size/S

#225 Add pipeline v0.20.0 to the docs
  sync/config/pipelines.yaml
Labels: approved, lgtm, size/S

#235 Renaming branches: handling operator repository
  content/en/docs/Overview/_index.md
Labels: approved, lgtm, size/XS

#239 Update the development.md
  DEVELOPMENT.md
Labels: approved, lgtm, size/S

#241 Add missing CLI releases to the docs 📖
  sync/config/cli.yaml
Labels: approved, lgtm, size/S

#232 Renaming branches: handling community repository
  CONTRIBUTING.md
Labels: approved, lgtm, size/S

#233 Renaming branches: handling website repository
  content/en/doc-con-main.md
  themes/docsy/layouts/partials/page-meta-links.html
  tutorials/katacoda/getting-started/concepts.md
  tutorials/katacoda/getting-started/intro.md
  tutorials/katacoda/getting-started/src/tekton-katacoda/resources/git.yaml
  tutorials/katacoda/runs/intro.md
  tutorials/katacoda/tasks/intro.md
Labels: approved, lgtm, size/M

#242 Create a Roadmap for the repo
  roadmap.md
Labels: approved, kind/documentation, lgtm, size/S

#245 Regenerate asciinema demo to fix typo
  static/asciinema/demo.cast
Labels: approved, lgtm, size/XXL

#247 fix broken link in getting-started tutorial
  tutorials/katacoda/getting-started/concepts.md
Labels: approved, lgtm, size/XS

#248 Fix broken links in lists and indented text
  sync/requirements.txt
  sync/sync.py
  sync/test_sync.py
Labels: approved, kind/bug, lgtm, size/L

#244 Fix install instructions for deb-based distros
  content/en/docs/Getting Started/_index.md
Labels: approved, lgtm, size/XS

#249 Add pipelines v0.21.0
  sync/config/pipelines.yaml
Labels: approved, kind/documentation, lgtm, size/S
