Repository tektoncd/website, pull requests merged in 2022-11, with the labels that each got.

#470 Add Dashboard v0.30 docs
  sync/config/dashboard.yaml
Labels: size/XS, lgtm, approved

#459 update hugo to 0.104.3
  netlify.toml
Labels: size/XS, lgtm, approved

#472 Create blog contributions guidelines
  content/en/docs/Contribute/blog-guidelines.md
Labels: lgtm, approved, size/M

#466 Fix typos and make small improvements
  assets/scss/_styles_project.scss
  content/en/_index.html
  content/en/docs/Getting Started/_index.md
  content/en/docs/Getting Started/triggers.md
  layouts/community/list.html
  layouts/shortcodes/blocks/manifesto.html
Labels: lgtm, approved, size/M

#475 Update docsy version
  go.mod
  go.sum
Labels: size/XS, lgtm, approved

#476 wrong component name in docs
  content/en/docs/Getting Started/triggers.md
Labels: size/XS, lgtm, approved

#477 add pipeline v0.42
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/S
