Repository tektoncd/website, pull requests merged in 2022-05, with the labels that each got.

#367 Update concepts
  content/en/docs/Concepts/_index.md
  content/en/docs/Concepts/concept-model.md
  content/en/docs/Concepts/overview.md
Labels: lgtm, approved, size/L

#372 Remove references to the try page from the asciinema recording
  asciinema/scenario.sh
  static/asciinema/demo.cast
Labels: lgtm, approved, size/XXL

#371 Remove references to Katacoda tutorials
  content/en/_index.html
  content/en/try/_index.md
  content/en/try/icons/advanced.png
  content/en/try/icons/concept.png
  content/en/try/icons/control.png
  content/en/try/icons/custom.png
  content/en/try/icons/dashboard.png
  content/en/try/icons/getting-started.png
  content/en/try/icons/github.png
  content/en/try/icons/helm.png
  content/en/try/icons/jenkins.png
  content/en/try/icons/organize.png
  content/en/try/icons/run.png
  content/en/try/icons/task.png
  layouts/shortcodes/blocks/showcase.html
  layouts/try/baseof.html
  layouts/try/list.html
  layouts/try/single.html
Labels: lgtm, approved, size/L

#358 Add triggers v0.17.1, v0.18.0 and v0.19.0
  sync/config/triggers.yaml
Labels: lgtm, approved, size/S

#378 Include Tekton videos in Getting Started
  content/en/docs/Getting Started/_index.md
Labels: lgtm, approved, size/S

#382 Remove remaining reference to Try page on docs landing page
  content/en/docs/_index.md
Labels: size/XS, lgtm, approved

#380 Update netlify dev to avoid framework prompt
  netlify.toml
Labels: size/XS, lgtm, approved

#384 Add missing CLI releases
  sync/config/cli.yaml
Labels: lgtm, approved, size/S

#383 Sync Dashboard docs to the website
  .gitignore
  content/en/docs/Dashboard/_index.md
  sync/config/dashboard.yaml
Labels: lgtm, approved, size/L

#388 Add triggers v0.20.0
  sync/config/triggers.yaml
Labels: lgtm, approved, size/S
