Repository tektoncd/website, pull requests merged in 2022-07, with the labels that each got.

#400 Add v0.36 and v0.37 pipeline ref docs
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/S

#403 add more space to content on mobile (ui)
  assets/scss/_styles_project.scss
Labels: size/XS, lgtm, approved

#417 Add newest Pipelines release to sync configuration
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/S

#418 Bump Python runtime version to 3.8
  runtime.txt
Labels: size/XS, lgtm, approved

#413 Fix code typos
  content/en/docs/How-to guides/clone-repository.md
  content/en/docs/How-to guides/kaniko-build-push.md
Labels: lgtm, approved, size/M

#412 Editorial review
  content/en/docs/Getting Started/pipelines.md
  content/en/docs/Getting Started/tasks.md
Labels: lgtm, approved, size/M
