Repository tektoncd/website, pull requests merged in 2022-06, with the labels that each got.

#387 How to clone a git repo with Tekton
  content/en/docs/How-to guides/_index.md
  content/en/docs/How-to guides/clone-repository.md
Labels: lgtm, approved, size/XL

#391 Add Dashboard v0.27 docs
  sync/config/dashboard.yaml
Labels: size/XS, lgtm, approved

#394 How to build and push an image with Kaniko
  content/en/docs/How-to guides/clone-repository.md
  content/en/docs/How-to guides/kaniko-build-push.md
Labels: lgtm, approved, size/L

#397 Accessibility add alt to images
  layouts/shortcodes/blocks/cover.html
  layouts/shortcodes/blocks/manifesto.html
  layouts/shortcodes/blocks/partners-alternate.html
Labels: size/XS, lgtm, approved
