Repository tektoncd/website, pull requests merged in 2022-04, with the labels that each got.

#298 Create a Quickstart to run a Tekton task with Minikube
  content/en/docs/Getting Started/_index.md
  content/en/docs/Getting Started/pipelines.md
  content/en/docs/Getting Started/tasks.md
Labels: lgtm, approved, size/XL

#364 Fix example task
  content/en/docs/Getting Started/tasks.md
Labels: size/XS, lgtm, approved

#370 adding two major releases
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/S
