Repository tektoncd/website, pull requests merged in 2022-09, with the labels that each got.

#423 Accessibility update footer github link
  layouts/partials/footer.html
Labels: size/XS, lgtm, approved

#440 Add Dashboard v0.29 docs
  sync/config/dashboard.yaml
Labels: size/XS, lgtm, approved

#438 Add Triggers v0.21.0
  sync/config/triggers.yaml
Labels: lgtm, approved, size/S

#439 Use generateName in pipelineruns
  content/en/docs/How-to guides/clone-repository.md
  content/en/docs/How-to guides/kaniko-build-push.md
Labels: lgtm, approved, size/M

#444 Add release-v0.40.x to website
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/S

#445 Pin Kubernetes version in getting started tutorial
  content/en/docs/Getting Started/tasks.md
Labels: size/XS, lgtm, approved

#446 Implement click-to-copy for code listings
  assets/js/click-to-copy.js
  assets/scss/_styles_project.scss
  layouts/partials/head.html
  layouts/partials/scripts.html
Labels: lgtm, approved, size/L

#449 Fix cookies modal not clossing
  layouts/partials/head.html
  layouts/partials/scripts.html
Labels: size/XS, lgtm, approved

#442 update hugo to 0.104.0
  netlify.toml
Labels: size/XS, lgtm, approved

#450 Update Docker to use Netlify and Ubuntu
  Dockerfile
  Makefile
  docker-compose.yaml
  layouts/partials/scripts.html
  netlify.toml
Labels: lgtm, approved, size/M
