Repository tektoncd/website, pull requests merged in 2022-10, with the labels that each got.

#454 Bump docsy version up to v0.4.0
  go.mod
  go.sum
Labels: size/XS, lgtm, approved

#458 Create getting started with triggers
  content/en/docs/Getting Started/pipelines.md
  content/en/docs/Getting Started/tasks.md
  content/en/docs/Getting Started/triggers.md
  static/images/TriggerFlow.svg
Labels: lgtm, approved, size/XL

#451 Create installation section
  content/en/docs/Concepts/_index.md
  content/en/docs/How-to guides/_index.md
  content/en/docs/Installation/_index.md
  content/en/docs/Installation/local-installation.md
  content/en/docs/Installation/pipelines.md
  content/en/docs/Installation/triggers.md
  content/en/docs/_index.md
Labels: lgtm, approved, size/M

#452 Create vendor docs folder
  config.toml
  content/en/docs/Contribute/doc-con-content.md
  content/en/docs/Contribute/doc-con-formatting.md
  content/en/docs/Contribute/doc-con-writing.md
  content/en/docs/Contribute/run-locally.md
  content/en/docs/Contribute/vendor-docs.md
  content/en/vendor/README.md
  content/en/vendor/disclaimer.md
Labels: lgtm, approved, size/XL

#460 Fix typo in kaniko-build-push.md
  content/en/docs/How-to guides/kaniko-build-push.md
Labels: size/XS, lgtm, approved

#461 Create community page
  assets/scss/_styles_project.scss
  content/en/community/_index.md
  layouts/community/list.html
  layouts/partials/community-links.html
Labels: lgtm, approved, size/L

#464 Bump docsy version up to v0.5.1
  content/en/vendor/README.md
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#468 Add pipeline v0.41.x
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/S
