Repository tektoncd/website, pull requests merged in 2023-04, with the labels that each got.

#534 Blog post announcing cdCon GitOpsCon Tekton talks
  content/en/blog/2023/cdcon-gitopscon/banner.png
  content/en/blog/2023/cdcon-gitopscon/index.md
Labels: lgtm, approved, size/M

#535 blog/2023/cdcon-gitopscon: Make banner image more high-contrast.
  content/en/blog/2023/cdcon-gitopscon/banner.png
Labels: size/XS, lgtm, approved

#536 Fix typo in blog front matter
  content/en/blog/2022/graduation/index.md
  content/en/blog/2023/cdcon-gitopscon/index.md
Labels: size/XS, lgtm, approved

#537 Initial revision of SLSA blog post.
  content/en/blog/2023/slsa-2/example.png
  content/en/blog/2023/slsa-2/index.md
  content/en/blog/2023/slsa-2/levels.png
  content/en/blog/2023/slsa-2/p1.png
  content/en/blog/2023/slsa-2/p2.png
  content/en/blog/2023/slsa-2/p3.png
  content/en/blog/2023/slsa-2/p4.png
  content/en/blog/2023/slsa-2/provenance.png
Labels: lgtm, approved, size/L

#538 Add Dashboard v0.35 LTS docs
  sync/config/dashboard.yaml
Labels: size/XS, lgtm, approved

#539 Update pipeline releases
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/S
