Repository tektoncd/website, pull requests merged in 2023-10, with the labels that each got.

#562 Redirect /predicate/chains to Chains documentation.
  .gitignore
  public/_redirects
Labels: size/XS, lgtm, approved

#565 Update tasks.md for bumping kubernetes version to minimum requirement.
  content/en/docs/Getting-started/tasks.md
Labels: size/XS, lgtm, approved

#564 Update pipelines.md to reflect actual observed pipeline output
  content/en/docs/Getting-started/pipelines.md
Labels: size/XS, lgtm, approved

#567 add operator v0.68.x docs
  sync/config/operator.yaml
Labels: kind/documentation, lgtm, approved, size/S

#570 Update pipeline releases
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/S

#569 Update Slack invite link
  layouts/partials/community-links.html
Labels: size/XS, lgtm, approved
