Repository tektoncd/website, pull requests merged in 2023-03, with the labels that each got.

#516 Add release selector to docs
  .gitignore
  assets/scss/_styles_project.scss
  config.yaml
  content/en/docs/Installation/pipelines.md
  layouts/docs/baseof.html
  layouts/partials/release-selector.html
  sync/config/pipelines.yaml
  sync/sync.py
  templates/release-switcher.js.template
Labels: lgtm, approved, size/L

#523 Add instructions to embed code samples in docs
  content/en/docs/Contribute/doc-con-formatting.md
  content/en/docs/Contribute/samples/pipeline1.yaml
  content/en/docs/Contribute/samples/pipeline2.yaml
  content/en/docs/Contribute/samples/task.yaml
Labels: lgtm, approved, size/M

#525 Add new analytics ID
  Makefile
  analytics.txt
  config.yaml
Labels: size/XS, lgtm, approved

#524 Add Triggers v0.23.0
  sync/config/triggers.yaml
Labels: lgtm, approved, size/S, kind/misc

#528 Update analytics template
  layouts/partials/head.html
Labels: size/XS, lgtm, approved

#529 Remove metadata.description from show-readme.yaml
  content/en/docs/How-to-guides/clone-repository.md
Labels: size/XS, lgtm, approved

#532 Add Pipelines v0.46 docs and remove EOL releases
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/L
