Repository tektoncd/website, pull requests merged in 2023-01, with the labels that each got.

#479 Sync TektonCD CLI releases
  sync/config/cli.yaml
Labels: lgtm, approved, size/M

#491 fix lts version doc href
  templates/version-switcher.js.template
Labels: size/XS, lgtm, approved

#485 Add Dashboard v0.31 docs
  sync/config/dashboard.yaml
Labels: size/XS, lgtm, approved

#488 Mark Tekton as graduated on the homepage
  layouts/shortcodes/blocks/manifesto.html
Labels: size/XS, lgtm, approved

#496 quick fix for typo
  content/en/docs/Getting Started/tasks.md
Labels: size/XS, lgtm, approved

#497 Add Dashboard v0.32 docs
  sync/config/dashboard.yaml
Labels: kind/documentation, lgtm, approved, size/S

#495 Add recent pipelines releases to sync config
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/S

#474 update hugo to 0.105.0
  netlify.toml
Labels: size/XS, lgtm, approved

#501 Fix link rewrites
  sync/sync.py
Labels: kind/bug, size/XS, lgtm, approved
