Repository tektoncd/website, pull requests merged in 2024-06, with the labels that each got.

#609 add operator v0.71.x docs
  sync/config/operator.yaml
Labels: lgtm, approved, size/S

#612 Created Pipelines release for v0.61
  sync/config/pipelines.yaml
Labels: size/XS, lgtm, approved, kind/misc

#613 Add Dashboard v0.48.0 docs
  sync/config/dashboard.yaml
Labels: kind/documentation, size/XS, lgtm, approved
