Repository tektoncd/website, pull requests merged in 2024-08, with the labels that each got.

#618 Minor rewording in tasks.md
  content/en/docs/Getting-started/tasks.md
Labels: size/XS, lgtm, approved

#616 Update kubernetes version in Pipelines getting started docs
  content/en/docs/Getting-started/tasks.md
Labels: kind/documentation, size/XS, lgtm, approved

#617 Add Dashboard v0.49.0 docs and remove the EOL v0.38.0
  sync/config/dashboard.yaml
Labels: kind/documentation, lgtm, approved, size/S
