Repository tektoncd/website, pull requests merged in 2024-05, with the labels that each got.

#602 Add Triggers v0.27.x release
  sync/config/triggers.yaml
Labels: lgtm, approved, size/L, kind/misc

#603 Add Pipelines v0.59.x release
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/S, kind/misc

#605 Remove EOL v0.47.x and v0.44.x releases for Pipelines
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/S, kind/misc

#600 Add Dashboard v0.46 LTS and v0.47 docs and remove EOL releases
  sync/config/dashboard.yaml
Labels: kind/documentation, lgtm, approved, size/S

#606 Update pipeline release v0.60.x
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/S
