Repository tektoncd/website, pull requests merged in 2024-02, with the labels that each got.

#589 add operator v0.70.x docs
  sync/config/operator.yaml
Labels: size/XS, lgtm, approved

#590 Add Triggers v0.26.1
  sync/config/triggers.yaml
Labels: lgtm, approved, size/S, kind/misc

#588 Update mermaid to fix Results data model diagram
  layouts/partials/scripts.html
Labels: size/XS, lgtm, approved, kind/misc

#593 Update pipeline release v0.57.x
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/S
