Repository tektoncd/website, pull requests merged in 2025-06, with the labels that each got.

#651 Add a blog entry about Tekton Pipelines 1.0
  content/en/blog/2025/ghcr-migration/index.md
  content/en/blog/2025/tekton-pipeline-v1.0.0/index.md
Labels: lgtm, approved, size/S

#657 Add Dashboard v0.59.0 docs
  sync/config/dashboard.yaml
Labels: kind/documentation, size/XS, lgtm, approved

#655 Update pipeline versions on the website
  sync/config/pipelines.yaml
Labels: lgtm, approved, size/M
