Repository tektoncd/website, pull requests merged in 2025-07, with the labels that each got.

#660 Update ghcr migration blog entry.
  DEVELOPMENT.md
  content/en/blog/2025/ghcr-migration/index.md
Labels: lgtm, approved, size/M

#661 Add Custom Icons for LinkedIn, Slack, and Twitter on Website #577
  config.yaml
Labels: size/XS, lgtm, approved

#663 feat: refresh getting started
  content/en/docs/Getting-started/pipelines.md
  content/en/docs/Getting-started/samples/build-push.yaml
  content/en/docs/Getting-started/samples/provenance.json
  content/en/docs/Getting-started/supply-chain-security.md
  content/en/docs/Getting-started/tasks.md
  content/en/docs/Getting-started/triggers.md
Labels: lgtm, approved, size/L

#664 Add twoGiants as approver to website.
  OWNERS
Labels: lgtm, approved, size/S

#665 Fix image links in blogpost
  content/en/blog/2025/protect-signing-secrets-for-tekton-chains-using-confidential-computing/index.md
Labels: lgtm, approved, size/S
